# Generated by Django 4.2.14 on 2024-11-14 14:48

import MultiCloudStorage.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CloudEncodedVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=MultiCloudStorage.storage_backends.VideoAzureStorage(),
                        upload_to="videos/",
                    ),
                ),
                ("encoded", models.BooleanField(default=False)),
                ("deleted_original_video", models.BooleanField(default=False)),
                (
                    "encoding_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dash_url", models.URLField(blank=True, null=True)),
                ("hls_url", models.URLField(blank=True, null=True)),
                ("log", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
        ),
    ]
